import { z } from 'zod'
import { DriftIssueId, SourceReference, Timestamp } from './common.js'

export const DriftSeverity = z.enum(['error', 'warning', 'info'])
export type DriftSeverity = z.infer<typeof DriftSeverity>

/**
 * A structured record of an inconsistency observed between two sources
 * of truth for the node it sits on. Generated by build-cycle skills
 * (braid-extract / braid-model) when they detect that intent and code
 * (or two code layers, or two intent files) disagree.
 *
 * Drift is a derived observation, not a persistent fact: each build
 * cycle recomputes the list. There is no "resolved" state — fix the
 * underlying source and the issue stops being raised. To silence a
 * known-and-accepted drift without fixing it, list its description in
 * `node.metadata.acknowledgedDrifts`.
 *
 * The skill-side taxonomy (which dimensions to compare, how to write
 * `description`) lives in the skill prompt references, not in this
 * schema, so adding a new dimension does not require a migration.
 */
export const DriftIssue = z.object({
  id: DriftIssueId,
  description: z.string().min(1),
  severity: DriftSeverity,
  sourceReferences: z.array(SourceReference).min(2),
  raisedAt: Timestamp,
})
export type DriftIssue = z.infer<typeof DriftIssue>
